language: julia

os:
  - linux

julia:
  - release
  - nightly

notifications:
  email: true

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fbc27706f3c4c51452e9

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

script:
  - julia --check-bounds=yes --code-coverage=user --track-allocation=user -e 'Pkg.clone(pwd()); Pkg.build("HydrocarbonNets"); Pkg.test("HydrocarbonNets"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("HydrocarbonNets")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
